# 行列演算
1. ベクトルの定義
2. 行列の定義
3. 転置
4. 逆行列
5. 行列積

In [1]:
import numpy as np

In [2]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [3]:
x.shape

(3, 1)

In [7]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [5]:
# 転置(Transpose)
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [11]:
# 逆行列(linalg: linear Algebra: 線形代数)
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
# 行列積
XX_inv = np.dot(X, X_inv)
XX_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## NumPyでよく使用する処理

In [16]:
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row, col = B.shape

In [17]:
row

2

In [18]:
col

3

In [19]:
for b in B:
    print(b)
    print('----------------------------')

[1 2 3]
----------------------------
[4 5 6]
----------------------------


# 重回帰分析の計算

1. ベクトルの定義
2. 行列の定義
3. 転置
4. 逆行列
5. 行列積

In [22]:
import numpy as np

In [25]:
# 行列X
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9],
])

X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [27]:
# ベクトル
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

y

array([[1],
       [5],
       [6],
       [8]])

In [28]:
# 内積を使ってXのTとXの掛け算を行う
XtX = np.dot(X.T, X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [30]:
# 逆行列
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [33]:
# XのTとYの内積
Xty = np.dot(X.T, y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [34]:
w = np.dot(XtX_inv, Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# scikit-learn

In [35]:
import sklearn
sklearn.__version__

'1.1.1'

In [36]:
import numpy as np
# 行列
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9],
])
# ベクトル
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

In [40]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=False)

In [41]:
# モデルの学習 <- パラメータの調整
model.fit(X, y)

LinearRegression(fit_intercept=False)

In [42]:
# 調整後のパラメータの確認
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [43]:
# 予測精度の確認(決定係数 0 ~ 1)
model.score(X, y)

0.6923076923076923

In [44]:
x_new = np.array([[1, 3, 6]])
x_new

array([[1, 3, 6]])

In [45]:
y_pred = model.predict(x_new)
y_pred

array([[5.42857143]])