In [2]:
import numpy as np
import pandas as pd

## ベクトルとブロードキャスト

In [3]:
# ベクトル
vec_1 = np.array([1, 5, 8, 13, 4])
vec_2 = np.array([2, 3, 5, 10, 98])

In [4]:
vec_1

array([ 1,  5,  8, 13,  4])

In [5]:
vec_2

array([ 2,  3,  5, 10, 98])

In [6]:
vec_1 + vec_2

array([  3,   8,  13,  23, 102])

In [7]:
vec_1 - vec_2

array([ -1,   2,   3,   3, -94])

In [8]:
vec_1 * vec_2

array([  2,  15,  40, 130, 392])

In [9]:
vec_1 / vec_2

array([0.5       , 1.66666667, 1.6       , 1.3       , 0.04081633])

In [10]:
# ベクトル
vec_1 = np.array([1, 5, 8, 13])
vec_2 = np.array([2])
vec_3 = np.array([2, 3])

In [11]:
# ブロードキャスト --- 長さが足りない場合は、それを補う
vec_1 + vec_2

array([ 3,  7, 10, 15])

In [12]:
# ブロードキャスト --- 長さが足りない要素は必ずリストが1でなければならない
vec_1 + vec_3

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
# 普通の数でもOK
vec_1 + 1

## ベクトルの要素抽出

In [13]:
vec_1 = np.array([1, 5, 8, 13, 4])

In [14]:
# インデックス4を抽出
vec_1[4]

4

In [15]:
# インデックス1 ~ 3を抽出
vec_1[1:4]

array([ 5,  8, 13])

In [16]:
# 論理値ベクトル
vec_bool = np.array([True, False, True, True, False])

In [17]:
# 論理値ベクトルが Trueのところ(インデックス0, 2, 3)を抽出
vec_1[vec_bool]

array([ 1,  8, 13])

In [18]:
# 論理値ベクトルはとある条件のとき、〇〇をするといった感じで使われる
# 5以上の要素を抽出
vec_1[vec_1 >= 5]

array([ 5,  8, 13])

In [19]:
vec_1 > 5

array([False, False,  True,  True, False])

## ベクトルの便利い函数

In [20]:
# ベクトルの総和
np.sum(vec_1)

31

In [21]:
# ベクトルの平均
np.average(vec_1)

6.2

In [23]:
# ベクトルの中央値(ベクトルを小さい順に並べた時に真ん中にくる数をさす)
np.median(vec_1)

5.0

In [24]:
# 最大値
np.max(vec_1)

13

In [25]:
# 最小値
np.min(vec_1)

1

In [27]:
# 分散(データのばらつき)
np.var(vec_1)

16.56

In [29]:
# 標準偏差(分散にルートをとったもの)
np.std(vec_1)

4.069397989875161

In [30]:
# 論理値ベクトル
vec_bool

array([ True, False,  True,  True, False])

In [33]:
# np.sumでTRUEの個数を算出
print(f'TRUEの総和 = {np.sum(vec_bool)}')

TRUEの総和 = 3


In [34]:
# np.averageでTRUEの割合を算出
print(f'TRUEの割合 = {np.average(vec_bool)}')

TRUEの割合 = 0.6


## 規則的なベクトルの作成

In [35]:
# 1から10までの等差1の等差ベクトル(等差 = 隣り合う数値の差)
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# 1から10までの長さ4の等差ベクトル
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [38]:
# 1を3回繰り返す
np.repeat(1,3)

array([1, 1, 1])

In [39]:
# 1を3回、2を3回繰り返す
np.repeat(np.array([1,2]), 3)

array([1, 1, 1, 2, 2, 2])

In [40]:
# 1を3回繰り返す
np.tile(1,3)

array([1, 1, 1])

In [41]:
# 1を3回、2を3回繰り返す
np.tile(np.array([1,2]), 3)

array([1, 2, 1, 2, 1, 2])

## 論理値ベクトルの作成方法

### 条件を満たしたかどうかでTRUEとFALSEを判定し、その判定結果を論理値ベクトルとする

In [45]:
# ベクトル
x = np.arange(1, 11, 1)
y = np.array([1, 7, 4, 6, 2])
y_2 = np.tile(y, 2)

In [46]:
# xとy_2は等しいか
x == y_2

array([ True, False, False, False, False, False,  True, False, False,
       False])

In [47]:
# xとy_2は等しくないか
x != y_2

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [48]:
# xとy_2以上か?
x >= y_2

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
# xはyに含まれるか?
np.isin(x,y)

array([ True,  True, False,  True, False,  True,  True, False, False,
       False])

## 論理値ベクトルの計算

In [50]:
# キャベツのサイズを示したベクトル
vec_size = np.array([7, 13, 5, 25, 38, 57, 18, 9, 32, 28])

In [53]:
# サイズは10以上か?
vec_bool_1 = vec_size >= 10

# サイズは30以下か
vec_bool_2 = vec_size <= 30

In [59]:
vec_bool_1

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True])

In [60]:
vec_bool_2

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True])

In [63]:
# AND
vec_bool_1 & vec_bool_2

array([False,  True, False,  True, False, False,  True, False, False,
        True])

In [64]:
# OR
vec_bool_1 | vec_bool_2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
# XOR
vec_bool_1 ^ vec_bool_2

array([ True, False,  True, False,  True,  True, False,  True,  True,
       False])

In [ ]:
# NOT
vec_bool_1  vec_bool_2